FROM node:22

WORKDIR /usr/src/app

# Copy app source code
COPY package*.json ./
RUN npm install
COPY . .

# Expose your app port
EXPOSE 3000

# Start your Node.js app (adjust as necessary)
CMD ["node", "server.js"]
