apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-nodejs-config
data:
  APPDYNAMICS_AGENT_APPLICATION_NAME: nodejs-auto-ins
  APPDYNAMICS_AGENT_ACCOUNT_NAME: <VALUE>
  APPDYNAMICS_CONTROLLER_HOST_NAME: <VALUE>
  APPDYNAMICS_CONTROLLER_PORT: <VALUE>
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: <VALUE>
  APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: <VALUE>
  APPDYNAMICS_AGENT_NODE_NAME: <VALUE>
  APPDYNAMICS_LOGGER_LEVEL: <VALUE>
  APPDYNAMICS_AGENT_TIER_NAME: <VALUE>