apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-python-config
data:
  APPDYNAMICS_TCP_COMM_PORT: <Value>
  APPDYNAMICS_AGENT_APPLICATION_NAME: <Value>
  APPDYNAMICS_AGENT_REUSE_NODE_NAME: <Value>
  APPDYNAMICS_AGENT_ACCOUNT_NAME: <Value>
  APPDYNAMICS_CONTROLLER_HOST_NAME: <Value>
  APPDYNAMICS_CONTROLLER_PORT: <Value>
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: <Value>
  APPDYNAMICS_AGENT_NODE_NAME: <value>