apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypython-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypython-app
  template:
    metadata:
      labels:
        app: mypython-app
    spec:
      containers:
        - name: mypython-app
          image: sidecar-python-app:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APPDYNAMICS_AGENT_APPLICATION_NAME
              value : <value>
            - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
              value : <value>
            - name: APPDYNAMICS_CONTROLLER_HOST_NAME
              value: <value>
            - name: APPDYNAMICS_CONTROLLER_PORT
              value: <value>
            - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
              value: <value>
            - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX
              value: <value>
            - name: APPDYNAMICS_AGENT_NODE_NAME
              value: <value>
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: <value>
            - name: APPDYNAMICS_LOGGER_LEVEL
              value: <value>
            - name: APPDYNAMICS_TCP_COMM_PORT
              value: "9091"
          env:
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: <value>
            - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX
              value: <value>
            - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: appd-agent-secret
                  key: access-key
        - name: proxy
          image: appdynamics/dl-proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
              protocol: TCP
          env:
            - name: APPDYNAMICS_DEBUG_LOG
              value: "on"
            - name: APPDYNAMICS_LOGGING_LEVEL
              value: "debug"
            - name: APPDYNAMICS_TCP_COMM_HOST
              value: "0.0.0.0"
            - name: APPDYNAMICS_TCP_COMM_PORT
              value: "9091"
            - name: APPDYNAMICS_TCP_PORT_RANGE
              value: "10000-10100"
          resources:
            limits:
              cpu: 500m
              memory: 900Mi
            requests:
              cpu: 400m
              memory: 600Mi
