apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-app:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: appd-agent
          mountPath: /opt/appdynamics
        env:
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value : <value>
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value : <value>
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: <value>
        - name: APPDYNAMICS_CONTROLLER_PORT
          value: <value>
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          value: <value>
        - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX
          value: <value>
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: <value>
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: <value>
        - name: APPDYNAMICS_LOGGER_LEVEL
          value: <value>
        - name: NODE_OPTIONS
          value: '--require /opt/appdynamics/shim.js'
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appd-agent-secret
              key: access-key
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            export UNIQUE_HOST_ID=$(sed -rn '1s#.*/##; 1s/(.{12}).*/\1/p' /proc/self/cgroup)
            npm start
      initContainers:
      - name: appd-agent-attach
        image: appd-nodejs-agent:v1
        command: ["cp", "-ra", "/opt/appdynamics/.", "/opt/temp"]
        volumeMounts:
        - name: appd-agent
          mountPath: /opt/temp
      volumes:
      - name: appd-agent
        emptyDir: {}