apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-nodejs-config
data:
  APPDYNAMICS_AGENT_APPLICATION_NAME: <value>
  APPDYNAMICS_AGENT_ACCOUNT_NAME: <value>
  APPDYNAMICS_CONTROLLER_HOST_NAME: <value>
  APPDYNAMICS_CONTROLLER_PORT: <value>
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: <value>
  APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: <value>
  APPDYNAMICS_AGENT_NODE_NAME: <value>
  APPDYNAMICS_LOGGER_LEVEL: <value>
  APPDYNAMICS_AGENT_TIER_NAME: <value>
  NODE_OPTIONS: '--require /opt/appdynamics/shim.js'
  
  # variables required to send transaction analytics data
  APPDYNAMICS_ANALYTICS_HOST_NAME: <value>
  APPDYNAMICS_ANALYTICS_PORT: <value>
  APPDYNAMICS_ANALYTICS_SSL_ENABLED: <value>